/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OWLapi;

import MCommon.Global;
import static MCommon.Global.knowledgeBase;
import MDataProcessing.Assertion.ConceptAssertion;
import MDataProcessing.Assertion.RoleAssertion;
import MDataProcessing.ConceptProcessing;
import MDataProcessing.DataProcessing;
import MDataProcessing.Individual.ConceptIndividuals;
import MDataProcessing.RoleProcessing;
import MKnowledge.KnowledgeBase;
import com.clarkparsia.owlapiv3.OWL;
import static com.clarkparsia.pellet.utils.TermFactory.inv;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import static java.util.Collections.list;
import java.util.HashSet;
import java.util.Map;
import static java.util.Objects.hash;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import jdk.nashorn.internal.runtime.regexp.JoniRegExp;
import org.semanticweb.HermiT.Reasoner;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLAnnotation;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLException;
import org.semanticweb.owlapi.model.OWLIndividual;
import org.semanticweb.owlapi.model.OWLObjectProperty;
import org.semanticweb.owlapi.model.OWLOntologyFormat;
import org.semanticweb.owlapi.reasoner.OWLReasoner;

/**
 *
 * @author thangdn
 */
public class HomeForm extends javax.swing.JFrame {
    
    
    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtreeConcept = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTreeRole = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lists = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTreeData = new javax.swing.JTree();
        javax.swing.JPanel jPanelRole = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfRangeRole = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfDomainRole = new javax.swing.JTextField();
        jbAddRole = new javax.swing.JButton();
        jPanelConcept = new javax.swing.JPanel();
        jtfnameConcept = new javax.swing.JTextField();
        jbAddConcept = new javax.swing.JButton();
        jPanelData = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtfDataRange = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfDataDomain = new javax.swing.JTextField();
        jbadData = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmbtLoadOntology = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jmbtExit = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jmAbout = new javax.swing.JMenu();
        jmbtAbout = new javax.swing.JCheckBoxMenuItem();

        jMenu8.setText("File");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jtreeConcept.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jtreeConcept);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTreeRole.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jTreeRole);

        jLabel1.setText("Concepts");

        jLabel2.setText("Roles");

        lists.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lists);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTreeData.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane4.setViewportView(jTreeData);

        jLabel4.setText("Range:");

        jLabel5.setText("Domain:");

        jbAddRole.setText("Add Role");

        javax.swing.GroupLayout jPanelRoleLayout = new javax.swing.GroupLayout(jPanelRole);
        jPanelRole.setLayout(jPanelRoleLayout);
        jPanelRoleLayout.setHorizontalGroup(
            jPanelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoleLayout.createSequentialGroup()
                .addGroup(jPanelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfRangeRole)
                    .addComponent(jtfDomainRole)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRoleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAddRole)
                .addContainerGap())
        );
        jPanelRoleLayout.setVerticalGroup(
            jPanelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoleLayout.createSequentialGroup()
                .addGroup(jPanelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtfRangeRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfDomainRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAddRole)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jbAddConcept.setText("Add Concept");

        javax.swing.GroupLayout jPanelConceptLayout = new javax.swing.GroupLayout(jPanelConcept);
        jPanelConcept.setLayout(jPanelConceptLayout);
        jPanelConceptLayout.setHorizontalGroup(
            jPanelConceptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConceptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConceptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfnameConcept)
                    .addGroup(jPanelConceptLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbAddConcept))))
        );
        jPanelConceptLayout.setVerticalGroup(
            jPanelConceptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConceptLayout.createSequentialGroup()
                .addComponent(jtfnameConcept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAddConcept)
                .addGap(34, 34, 34))
        );

        jLabel6.setText("Range:");

        jLabel7.setText("Domain:");

        jbadData.setText("Add Data");

        javax.swing.GroupLayout jPanelDataLayout = new javax.swing.GroupLayout(jPanelData);
        jPanelData.setLayout(jPanelDataLayout);
        jPanelDataLayout.setHorizontalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataLayout.createSequentialGroup()
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDataRange)
                    .addComponent(jtfDataDomain)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbadData)
                .addContainerGap())
        );
        jPanelDataLayout.setVerticalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataLayout.createSequentialGroup()
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDataRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(15, 15, 15)
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfDataDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbadData))
        );

        jLabel3.setText("Name:");

        jMenu1.setText("File");

        jmbtLoadOntology.setSelected(true);
        jmbtLoadOntology.setText("Load ontology");
        jmbtLoadOntology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbtLoadOntologyActionPerformed(evt);
            }
        });
        jMenu1.add(jmbtLoadOntology);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Save");
        jMenu1.add(jCheckBoxMenuItem2);

        jmbtExit.setSelected(true);
        jmbtExit.setText("Exit");
        jmbtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbtExitActionPerformed(evt);
            }
        });
        jMenu1.add(jmbtExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("reasoner");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Hermit");
        jMenu2.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("Pellet");
        jMenu2.add(jCheckBoxMenuItem4);

        jMenuBar1.add(jMenu2);

        jmAbout.setText("About");

        jmbtAbout.setSelected(true);
        jmbtAbout.setText("About");
        jmbtAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbtAboutActionPerformed(evt);
            }
        });
        jmAbout.add(jmbtAbout);

        jMenuBar1.add(jmAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelConcept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jPanelRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelConcept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmbtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbtExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmbtExitActionPerformed

    private void jmbtAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbtAboutActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_jmbtAboutActionPerformed
    
    
    
    private void jmbtLoadOntologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbtLoadOntologyActionPerformed
        JFileChooser fileChooser = new JFileChooser("\\home\\thangdn");
        int returnValue = fileChooser.showOpenDialog(null);
        jtreeConcept.removeAll();
        if (returnValue == JFileChooser.APPROVE_OPTION) {

            File selectedFile = fileChooser.getSelectedFile();

            Global.iriFileInput = IRI.create(selectedFile);
            Global.knowledgeBase = new KnowledgeBase(Global.iriFileInput);

            OWLOntologyFormat format = Global.knowledgeBase.getOntologyManager().getOntologyFormat(Global.knowledgeBase.getOntology());
            ConceptProcessing.createFrequentConceptsForFullVersion(Global.knowledgeBase);
            
            RoleProcessing.createFrequentRolesForFullVersion(Global.knowledgeBase);
            
            DataProcessing.createFrequentDatasForFullVersion(Global.knowledgeBase);
            
            jtreeConcept.setModel(new DefaultTreeModel(ConceptProcessing.top));
            
            jTreeRole.setModel(new DefaultTreeModel(RoleProcessing.top));
            
            jTreeData.setModel(new DefaultTreeModel(DataProcessing.top));
            
            jtreeConcept.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent me) {
                  doMouseClicked(me);
                }
                public void mousePressed ( MouseEvent e )
                {
                    if ( SwingUtilities.isRightMouseButton ( e ) )
                    {
                        TreePath path = jtreeConcept.getPathForLocation ( e.getX (), e.getY () );
                        Rectangle pathBounds = jtreeConcept.getUI ().getPathBounds ( jtreeConcept, path );
                        if ( pathBounds != null && pathBounds.contains ( e.getX (), e.getY () ) )
                        {
                            JPopupMenu menu = new JPopupMenu ();
                            
                            JMenuItem menuItem = new JMenuItem(new AbstractAction("Add new individual") {
                                public void actionPerformed(ActionEvent e) {
                                    System.out.print("xx");
                                }
                            });
                            menu.add (menuItem);
                            menu.show ( jtreeConcept, pathBounds.x, pathBounds.y + pathBounds.height );
                        }
                    }
                }
              });
            JPopupMenu popupMenu = new JPopupMenu();
            popupMenu.add(new JMenuItem(new AbstractAction("Show") {
                public void actionPerformed(ActionEvent e) { 
                    InfoIndividualForm aa = new InfoIndividualForm();
                    aa.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    aa.setVisible(true);
                }
            }));
            popupMenu.add(new JPopupMenu.Separator());
            popupMenu.add(new JMenuItem("Clear"));
            
            lists.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent me) {
                  
                  if (SwingUtilities.isRightMouseButton(me)
                      && !lists.isSelectionEmpty()
                      && lists.locationToIndex(me.getPoint())
                         == lists.getSelectedIndex()) {
                          popupMenu.show(lists, me.getX(), me.getY());
                          InfoIndividualForm.nameIndividual= lists.getSelectedValue().toString();
                          }
                      }
                   }
            );
        }
        
        
    }//GEN-LAST:event_jmbtLoadOntologyActionPerformed

    private void listsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listsValueChanged
        
    }//GEN-LAST:event_listsValueChanged
    void doMouseClicked(MouseEvent me) {
        //ArrayList<RoleAssertion> thang =Global.allFrequentRolesFull;
        TreePath tp = jtreeConcept.getPathForLocation(me.getX(), me.getY());
        if (tp != null)
        {
          System.out.print(tp.getPathComponent(tp.getPathCount()-1).toString());
          listConceptsValueChanged(tp);
        }
    }
    private void listConceptsValueChanged(TreePath tp) {                                          
        // TODO add your handling code here:
        ConceptAssertion conceptAssertion = ConceptProcessing.getConceptAssertionFromFrequentConceptsFull(tp.getPathComponent(tp.getPathCount()-1).toString());
        lists.removeAll();
        if (conceptAssertion != null) {
            ConceptIndividuals individuals = conceptAssertion.getIndividuals();
            Set<String> nameOfIndividuals = individuals.getIndividualsName();

            DefaultListModel modelIndividuals = new DefaultListModel();
            lists.setModel(modelIndividuals);
            modelIndividuals.clear();
            
            for (String strNameIndividual : nameOfIndividuals) {
                modelIndividuals.addElement(strNameIndividual);
            }
           
            //lblIndividuals.setText("Individuals_concept: " + String.valueOf(nameOfIndividuals.size()));
        }else{
            System.out.println("coceptAssertion null");
        }
    }     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanelConcept;
    private javax.swing.JPanel jPanelData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTree jTreeData;
    private javax.swing.JTree jTreeRole;
    private javax.swing.JButton jbAddConcept;
    private javax.swing.JButton jbAddRole;
    private javax.swing.JButton jbadData;
    private javax.swing.JMenu jmAbout;
    private javax.swing.JCheckBoxMenuItem jmbtAbout;
    private javax.swing.JRadioButtonMenuItem jmbtExit;
    private javax.swing.JCheckBoxMenuItem jmbtLoadOntology;
    private javax.swing.JTextField jtfDataDomain;
    private javax.swing.JTextField jtfDataRange;
    private javax.swing.JTextField jtfDomainRole;
    private javax.swing.JTextField jtfRangeRole;
    private javax.swing.JTextField jtfnameConcept;
    private javax.swing.JTree jtreeConcept;
    private javax.swing.JList lists;
    // End of variables declaration//GEN-END:variables
}
