/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OWLapi;

import MCommon.Global;
import MDataProcessing.Assertion.ConceptAssertion;
import MDataProcessing.Assertion.DataAssertion;
import MDataProcessing.Assertion.RoleAssertion;
import MDataProcessing.ConceptProcessing;
import MDataProcessing.DataProcessing;
import MDataProcessing.Individual.DataIndividual;
import MDataProcessing.Individual.RoleIndividual;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.SystemColor;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author thangdn
 */
public class InfoIndividualForm extends javax.swing.JFrame {
    public static String nameIndividual;
    private String mainNameIndividual;
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    /**
     * Creates new form InfoIndividualForm
     */
    public InfoIndividualForm() {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(screenSize.width - 50 ,screenSize.height - 200);
        initComponents();
        setIndivisual(InfoIndividualForm.nameIndividual);
        getInforIndividual();
               
    }
    
    public void setIndivisual(String nameIndividual)
    {
        this.mainNameIndividual=nameIndividual;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getInforIndividual()
    {
        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setBounds(0,0,this.getSize().width-5,this.getSize().height);
        //scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        getContentPane().add(scrollPane);

        JPanel borderlaoutpanel = new JPanel();
        scrollPane.setViewportView(borderlaoutpanel);
        borderlaoutpanel.setLayout(new BorderLayout(0, 0));

        JPanel columnpanel = new JPanel();
        borderlaoutpanel.add(columnpanel, BorderLayout.NORTH);
        columnpanel.setLayout(new GridLayout(0, 1, 0, 1));
        columnpanel.setBackground(Color.gray);
        int i=0;
        for(ConceptAssertion a:Global.allFrequentConceptsFull)
        {
            
            for (String col : a.getIndividuals().getIndividualsName()) {
                if(col.equals(this.mainNameIndividual))
                {
                    JButton ka=new JButton(new AbstractAction(a.getConceptName()) {
                                public void actionPerformed(ActionEvent e) {
                                    System.out.print("xx");
                                }});
                    JPanel rowPanel = new JPanel();
                    rowPanel.setPreferredSize(new Dimension(300,30));
                    columnpanel.add(rowPanel);
                    rowPanel.setLayout(null);
                    JLabel as = new JLabel(this.mainNameIndividual + " is ");
                    as.setBounds(20, 5, 200, 23);
                    rowPanel.add(as);
                    
                    ka.setBounds(200, 5, 200, 23);
                    rowPanel.add(ka);
                    if(i%2==0)
                        rowPanel.setBackground(SystemColor.inactiveCaptionBorder);
                    i++;
                }
            }
        }
        for(RoleAssertion a:Global.allFrequentRolesFull)
        {
            for (RoleIndividual col : a.getIndividuals().getIndividuals()) {
                if(col.getDomain().equals(this.mainNameIndividual)||col.getRange().equals(this.mainNameIndividual))
                {
                    JButton ka=new JButton(new AbstractAction(a.getRoleName()) {
                                public void actionPerformed(ActionEvent e) {
                                    System.out.print("xx");
                                }});
                    JPanel rowPanel = new JPanel();
                    rowPanel.setPreferredSize(new Dimension(300,30));
                    columnpanel.add(rowPanel);
                    rowPanel.setLayout(null);
                    JLabel as = new JLabel(col.getDomain() + " ");
                    as.setBounds(20, 5, 200, 23);
                    rowPanel.add(as);
                    
                    ka.setBounds(200, 5, 200, 23);
                    rowPanel.add(ka);
                    JLabel ass = new JLabel(" "+col.getRange());
                    ass.setBounds(400, 5, 200, 23);
                    rowPanel.add(ass);
                    if(i%2==0)
                        rowPanel.setBackground(SystemColor.inactiveCaptionBorder);
                    i++;
                }
            }
        }
        
        for(DataAssertion a:Global.allFrequentDatasFull)
        {
            //if(DataProcessing.isLeaf(a.getDataName()))
            for (DataIndividual col : a.getIndividuals().getIndividuals()) {
                if(col.getDomain().equals(this.mainNameIndividual)||col.getRange().equals(this.mainNameIndividual))
                {
                    JButton ka=new JButton(new AbstractAction(a.getDataName()) {
                                public void actionPerformed(ActionEvent e) {
                                    System.out.print("xx");
                                }});
                    JPanel rowPanel = new JPanel();
                    rowPanel.setPreferredSize(new Dimension(300,30));
                    columnpanel.add(rowPanel);
                    rowPanel.setLayout(null);
                    JLabel as = new JLabel(col.getDomain() + " ");
                    as.setBounds(20, 5, 200, 23);
                    rowPanel.add(as);
                    
                    ka.setBounds(200, 5, 200, 23);
                    rowPanel.add(ka);
                    JLabel ass = new JLabel(" "+col.getRange());
                    ass.setBounds(400, 5, 200, 23);
                    rowPanel.add(ass);
                    if(i%2==0)
                        rowPanel.setBackground(SystemColor.inactiveCaptionBorder);
                    i++;
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoIndividualForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoIndividualForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoIndividualForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoIndividualForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoIndividualForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
